export const class10Questions = [
    {
      question: "Who proposed the theory of relativity?",
      option1: "Isaac Newton",
      option2: "Albert Einstein",
      option3: "Niels Bohr",
      option4: "Galileo Galilei",
      ans: 2,
    },
    {
      question: "In chemistry, what is the Avogadro constant?",
      option1: "6.022 x 10^23",
      option2: "3.141 x 10^5",
      option3: "9.81 x 10^2",
      option4: "2.20 x 10^4",
      ans: 1,
    },
    {
      question: "Which Indian state is known as the 'Land of Five Rivers'?",
      option1: "Punjab",
      option2: "Haryana",
      option3: "Uttar Pradesh",
      option4: "Rajasthan",
      ans: 1,
    },
    {
      question: "What is the value of 'π' (pi) to six decimal places?",
      option1: "3.141592",
      option2: "3.142857",
      option3: "3.145926",
      option4: "3.148793",
      ans: 1,
    },
    {
      question: "Who discovered the neutron?",
      option1: "Marie Curie",
      option2: "Niels Bohr",
      option3: "Ernest Rutherford",
      option4: "James Chadwick",
      ans: 4,
    },
    {
      question: "What is the capital city of Brazil?",
      option1: "Rio de Janeiro",
      option2: "Brasília",
      option3: "Sao Paulo",
      option4: "Buenos Aires",
      ans: 2,
    },
    {
      question: "In physics, what is Hooke's Law related to?",
      option1: "Electricity",
      option2: "Gravity",
      option3: "Elasticity",
      option4: "Magnetism",
      ans: 3,
    },
    {
      question: "Who developed the first successful polio vaccine?",
      option1: "Jonas Salk",
      option2: "Louis Pasteur",
      option3: "Edward Jenner",
      option4: "Robert Koch",
      ans: 1,
    },
    {
      question: "Which mathematical concept is represented by the symbol 'Σ' (sigma)?",
      option1: "Summation",
      option2: "Integration",
      option3: "Differentiation",
      option4: "Multiplication",
      ans: 1,
    },
    {
      question: "What is the chemical formula for hydrogen peroxide?",
      option1: "H2O2",
      option2: "HCl",
      option3: "CO2",
      option4: "NaCl",
      ans: 1,
    },
    {
      question: "Which planet is known as the 'Blue Planet'?",
      option1: "Venus",
      option2: "Mars",
      option3: "Earth",
      option4: "Neptune",
      ans: 3,
    },
    {
      question: "In literature, who wrote the play 'Romeo and Juliet'?",
      option1: "Charles Dickens",
      option2: "William Shakespeare",
      option3: "Jane Austen",
      option4: "Mark Twain",
      ans: 2,
    },
    {
      question: "What is the process of nuclear fission used for?",
      option1: "Generating electricity",
      option2: "Food preservation",
      option3: "Carbon dating",
      option4: "Desalination",
      ans: 1,
    },
    {
      question: "Who proposed the concept of natural selection in evolution?",
      option1: "Charles Darwin",
      option2: "Gregor Mendel",
      option3: "Alfred Russel Wallace",
      option4: "Jean-Baptiste Lamarck",
      ans: 1,
    },
    {
      question: "What is the chemical symbol for gold?",
      option1: "Au",
      option2: "Ag",
      option3: "Fe",
      option4: "Cu",
      ans: 1,
    },
    {
      question: "In chemistry, what is the definition of a mole?",
      option1: "A small rodent",
      option2: "A unit of measurement for mass",
      option3: "A type of sauce",
      option4: "A chemical reaction",
      ans: 2,
    },
    {
      question: "Which gas is known as the 'silent killer'?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Carbon Monoxide",
      option4: "Nitrogen",
      ans: 3,
    },
    {
      question: "What is the capital city of Australia?",
      option1: "Sydney",
      option2: "Melbourne",
      option3: "Canberra",
      option4: "Brisbane",
      ans: 3,
    },
    {
      question: "What is the process by which plants make their own food?",
      option1: "Photosynthesis",
      option2: "Respiration",
      option3: "Transpiration",
      option4: "Fermentation",
      ans: 1,
    },
    {
      question: "In mathematics, what is a 'matrix'?",
      option1: "A type of equation",
      option2: "A set of numbers arranged in rows and columns",
      option3: "A geometric shape",
      option4: "A type of function",
      ans: 2,
    },
    {
      question: "What is the chemical formula for sulfuric acid?",
      option1: "HCl",
      option2: "H2SO4",
      option3: "CH4",
      option4: "NaOH",
      ans: 2,
    },
    {
      question: "Who discovered the double helix structure of DNA?",
      option1: "James Watson and Francis Crick",
      option2: "Rosalind Franklin",
      option3: "Linus Pauling",
      option4: "Gregor Mendel",
      ans: 1,
    },
    {
      question: "What is the value of 'e' (Euler's number) to five decimal places?",
      option1: "2.71828",
      option2: "3.14159",
      option3: "1.61803",
      option4: "2.23607",
      ans: 1,
    },
    {
      question: "Which gas is responsible for the smell of rotten eggs?",
      option1: "Hydrogen",
      option2: "Sulfur Dioxide",
      option3: "Methane",
      option4: "Ammonia",
      ans: 2,
    },
    {
      question: "Who is known as the 'Father of Modern Physics'?",
      option1: "Isaac Newton",
      option2: "Albert Einstein",
      option3: "Galileo Galilei",
      option4: "Niels Bohr",
      ans: 2,
    },
  ];
  export default class10Questions;