import class1Questions from "./class1Questions";

export const class2Questions = [
    {
      question: "What is the largest planet in our solar system?",
      option1: "Earth",
      option2: "Mars",
      option3: "Jupiter",
      option4: "Venus",
      ans: 3,
    },
    {
      question: "Which animal is known as the 'King of the Jungle'?",
      option1: "Elephant",
      option2: "Lion",
      option3: "Giraffe",
      option4: "Penguin",
      ans: 2,
    },
    {
      question: "What is the currency of Japan?",
      option1: "Yen",
      option2: "Dollar",
      option3: "Euro",
      option4: "Pound",
      ans: 1,
    },
    {
      question: "How many continents are there in the world?",
      option1: "5",
      option2: "6",
      option3: "7",
      option4: "8",
      ans: 2,
    },
    {
      question: "Who wrote 'Alice in Wonderland'?",
      option1: "J.K. Rowling",
      option2: "Lewis Carroll",
      option3: "Roald Dahl",
      option4: "Enid Blyton",
      ans: 2,
    },
    {
      question: "Which planet is known as the 'Red Planet'?",
      option1: "Mars",
      option2: "Venus",
      option3: "Jupiter",
      option4: "Saturn",
      ans: 1,
    },
    {
      question: "What is the process by which plants make their own food?",
      option1: "Photosynthesis",
      option2: "Respiration",
      option3: "Digestion",
      option4: "Answer not given",
      ans: 1,
    },
    {
      question: "What is the capital of Australia?",
      option1: "Sydney",
      option2: "Melbourne",
      option3: "Canberra",
      option4: "Brisbane",
      ans: 3,
    },
    {
      question: "What is the result of 6 + 4?",
      option1: "8",
      option2: "10",
      option3: "12",
      option4: "14",
      ans: 2,
    },
    {
      question: "Who is known as the 'Father of Computers'?",
      option1: "Alan Turing",
      option2: "Charles Babbage",
      option3: "Bill Gates",
      option4: "Steve Jobs",
      ans: 2,
    },
    {
      question: "Which gas do plants release during photosynthesis?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Nitrogen",
      option4: "Hydrogen",
      ans: 1,
    },
    {
      question: "What is the shape of a rectangle?",
      option1: "Square",
      option2: "Triangle",
      option3: "Circle",
      option4: "Rectangle",
      ans: 4,
    },
    {
      question: "Which famous scientist developed the theory of relativity?",
      option1: "Isaac Newton",
      option2: "Galileo Galilei",
      option3: "Albert Einstein",
      option4: "Nikola Tesla",
      ans: 3,
    },
    {
      question: "What is the smallest prime number?",
      option1: "0",
      option2: "1",
      option3: "2",
      option4: "3",
      ans: 3,
    },
    {
      question: "Who is the national poet of India?",
      option1: "Rabindranath Tagore",
      option2: "Sarojini Naidu",
      option3: "Bankim Chandra Chattopadhyay",
      option4: "Kazi Nazrul Islam",
      ans: 1,
    },
    {
      question: "How many sides does a hexagon have?",
      option1: "5",
      option2: "6",
      option3: "7",
      option4: "8",
      ans: 2,
    },
    {
      question: "What is the capital city of Brazil?",
      option1: "Buenos Aires",
      option2: "Rio de Janeiro",
      option3: "Brasília",
      option4: "Sao Paulo",
      ans: 3,
    },
    {
      question: "What is the result of 9 - 3?",
      option1: "4",
      option2: "5",
      option3: "6",
      option4: "7",
      ans: 3,
    },
    {
      question: "Which planet is known as the 'Morning Star'?",
      option1: "Mercury",
      option2: "Venus",
      option3: "Mars",
      option4: "Jupiter",
      ans: 2,
    },
    {
      question: "What is the largest mammal in the world?",
      option1: "Elephant",
      option2: "Blue Whale",
      option3: "Giraffe",
      option4: "Lion",
      ans: 2,
    },
    {
      question: "What is the currency of China?",
      option1: "Yuan",
      option2: "Yen",
      option3: "Dollar",
      option4: "Euro",
      ans: 1,
    },
    {
      question: "How many colors are there in a rainbow?",
      option1: "5",
      option2: "6",
      option3: "7",
      option4: "8",
      ans: 3,
    },
    {
      question: "Which gas do humans exhale when they breathe out?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Nitrogen",
      option4: "Hydrogen",
      ans: 2,
    },
    {
      question: "What is the result of 7 x 8?",
      option1: "49",
      option2: "56",
      option3: "64",
      option4: "72",
      ans: 2,
    },
  ];
  export default class2Questions;