export const class5Questions = [
    {
      question: "What is the largest ocean on Earth?",
      option1: "Atlantic Ocean",
      option2: "Indian Ocean",
      option3: "Southern Ocean",
      option4: "Pacific Ocean",
      ans: 4,
    },
    {
      question: "Who is known as the 'Father of the Indian Constitution'?",
      option1: "Jawaharlal Nehru",
      option2: "Sardar Patel",
      option3: "B.R. Ambedkar",
      option4: "Subhas Chandra Bose",
      ans: 3,
    },
    {
      question: "What is the result of 16 ÷ 4?",
      option1: "2",
      option2: "4",
      option3: "6",
      option4: "8",
      ans: 2,
    },
    {
      question: "Which gas do plants release during respiration?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Nitrogen",
      option4: "Methane",
      ans: 2,
    },
    {
      question: "Who wrote 'Discovery of India'?",
      option1: "Rabindranath Tagore",
      option2: "Jawaharlal Nehru",
      option3: "Sarojini Naidu",
      option4: "Mahatma Gandhi",
      ans: 2,
    },
    {
      question: "What is the result of 9²?",
      option1: "72",
      option2: "81",
      option3: "90",
      option4: "99",
      ans: 2,
    },
    {
      question: "Which planet is known as the 'Red Planet'?",
      option1: "Mars",
      option2: "Venus",
      option3: "Jupiter",
      option4: "Saturn",
      ans: 1,
    },
    {
      question: "What is the capital of Canada?",
      option1: "Toronto",
      option2: "Montreal",
      option3: "Vancouver",
      option4: "Ottawa",
      ans: 4,
    },
    {
      question: "What is the result of 7 x 8?",
      option1: "49",
      option2: "56",
      option3: "64",
      option4: "72",
      ans: 2,
    },
    {
      question: "Who discovered the law of electromagnetic induction?",
      option1: "Isaac Newton",
      option2: "Michael Faraday",
      option3: "James Clerk Maxwell",
      option4: "Nikola Tesla",
      ans: 2,
    },
    {
      question: "Which river is known as the 'River of Sorrows'?",
      option1: "Nile",
      option2: "Amazon",
      option3: "Yellow River",
      option4: "Indus",
      ans: 3,
    },
    {
      question: "What is the result of 12 + 5 × 3?",
      option1: "27",
      option2: "36",
      option3: "21",
      option4: "45",
      ans: 4,
    },
    {
      question: "Who was the first woman to win a Nobel Prize in Physics?",
      option1: "Marie Curie",
      option2: "Irene Joliot-Curie",
      option3: "Dorothy Crowfoot Hodgkin",
      option4: "Maria Goeppert Mayer",
      ans: 1,
    },
    {
      question: "What is the result of 11 - 6?",
      option1: "4",
      option2: "5",
      option3: "6",
      option4: "7",
      ans: 2,
    },
    {
      question: "Which gas is responsible for the greenhouse effect?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Nitrogen",
      option4: "Methane",
      ans: 2,
    },
    {
      question: "Who was the first President of the United States?",
      option1: "George Washington",
      option2: "Thomas Jefferson",
      option3: "John Adams",
      option4: "Abraham Lincoln",
      ans: 1,
    },
    {
      question: "What is the result of 17 ÷ 2?",
      option1: "7.5",
      option2: "8.5",
      option3: "8",
      option4: "9",
      ans: 2,
    },
    {
      question: "Who wrote 'The Diary of a Young Girl'?",
      option1: "Anne Frank",
      option2: "Harper Lee",
      option3: "J.K. Rowling",
      option4: "Mark Twain",
      ans: 1,
    },
    {
      question: "What is the capital of Mexico?",
      option1: "Madrid",
      option2: "Buenos Aires",
      option3: "Rio de Janeiro",
      option4: "Mexico City",
      ans: 4,
    },
    {
      question: "What is the result of 14 - 9?",
      option1: "3",
      option2: "4",
      option3: "5",
      option4: "6",
      ans: 3,
    },
    {
      question: "Which gas is known as 'Laughing Gas'?",
      option1: "Oxygen",
      option2: "Nitrous Oxide",
      option3: "Carbon Dioxide",
      option4: "Hydrogen",
      ans: 2,
    },
    {
      question: "Who is the 'Father of Modern Physics'?",
      option1: "Albert Einstein",
      option2: "Isaac Newton",
      option3: "Galileo Galilei",
      option4: "Stephen Hawking",
      ans: 1,
    },
    {
      question: "What is the result of 6³?",
      option1: "216",
      option2: "240",
      option3: "256",
      option4: "270",
      ans: 1,
    },
    {
      question: "Which Indian state is known as the 'Land of Five Rivers'?",
      option1: "Haryana",
      option2: "Punjab",
      option3: "Rajasthan",
      option4: "Gujarat",
      ans: 2,
    },
    {
      question: "What is the result of 10 + 2 × 5?",
      option1: "30",
      option2: "40",
      option3: "50",
      option4: "60",
      ans: 3,
    },
  ];
  export default class5Questions;