export const class12Questions = [
    {
      question: "What is the fundamental theorem of calculus?",
      option1: "Fundamental Theorem of Algebra",
      option2: "Fundamental Theorem of Arithmetic",
      option3: "Fundamental Theorem of Calculus",
      option4: "Fundamental Theorem of Trigonometry",
      ans: 3,
    },
    {
      question: "Who developed the theory of relativity along with Albert Einstein?",
      option1: "Niels Bohr",
      option2: "Max Planck",
      option3: "Werner Heisenberg",
      option4: "Mileva Marić",
      ans: 4,
    },
    {
      question: "In chemistry, what is the Henderson-Hasselbalch equation used for?",
      option1: "Calculating pH of a buffer solution",
      option2: "Balancing chemical equations",
      option3: "Determining atomic mass",
      option4: "Stoichiometry calculations",
      ans: 1,
    },
    {
      question: "Who proposed the theory of natural selection?",
      option1: "Charles Darwin",
      option2: "Gregor Mendel",
      option3: "Alfred Russel Wallace",
      option4: "Jean-Baptiste Lamarck",
      ans: 1,
    },
    {
      question: "What is the capital city of Australia?",
      option1: "Sydney",
      option2: "Melbourne",
      option3: "Canberra",
      option4: "Brisbane",
      ans: 3,
    },
    {
      question: "In physics, what is the equation for the conservation of energy?",
      option1: "E = mc^2",
      option2: "F = ma",
      option3: "P = mv",
      option4: "W = Fd",
      ans: 1,
    },
    {
      question: "Who is known as the 'Father of Modern Chemistry'?",
      option1: "Antoine Lavoisier",
      option2: "Dmitri Mendeleev",
      option3: "John Dalton",
      option4: "Robert Boyle",
      ans: 1,
    },
    {
      question: "Which gas is known as the 'silent killer'?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Carbon Monoxide",
      option4: "Nitrogen",
      ans: 3,
    },
    {
      question: "What is the chemical formula for methane?",
      option1: "CH3",
      option2: "CO2",
      option3: "C2H6",
      option4: "H2O",
      ans: 1,
    },
    {
      question: "In literature, who wrote the novel 'One Hundred Years of Solitude'?",
      option1: "Gabriel Garcia Marquez",
      option2: "Leo Tolstoy",
      option3: "George Orwell",
      option4: "F. Scott Fitzgerald",
      ans: 1,
    },
    {
      question: "What is the SI unit of electric charge?",
      option1: "Coulomb",
      option2: "Ampere",
      option3: "Volt",
      option4: "Ohm",
      ans: 1,
    },
    {
      question: "Who discovered the structure of DNA?",
      option1: "Watson and Crick",
      option2: "Rosalind Franklin",
      option3: "Gregor Mendel",
      option4: "James Watson",
      ans: 1,
    },
    {
      question: "What is the process of plants making their own food called?",
      option1: "Photosynthesis",
      option2: "Respiration",
      option3: "Transpiration",
      option4: "Fermentation",
      ans: 1,
    },
    {
      question: "Which gas is responsible for the greenhouse effect?",
      option1: "Oxygen",
      option2: "Methane",
      option3: "Carbon Dioxide",
      option4: "Nitrogen",
      ans: 3,
    },
    {
      question: "Who developed the first successful polio vaccine?",
      option1: "Jonas Salk",
      option2: "Louis Pasteur",
      option3: "Edward Jenner",
      option4: "Robert Koch",
      ans: 1,
    },
    {
      question: "What is the chemical symbol for gold?",
      option1: "Au",
      option2: "Ag",
      option3: "Fe",
      option4: "Cu",
      ans: 1,
    },
    {
      question: "Which mathematical concept is represented by the symbol 'Σ' (sigma)?",
      option1: "Summation",
      option2: "Integration",
      option3: "Differentiation",
      option4: "Multiplication",
      ans: 1,
    },
    {
      question: "Who discovered the neutron?",
      option1: "Marie Curie",
      option2: "Niels Bohr",
      option3: "Ernest Rutherford",
      option4: "James Chadwick",
      ans: 4,
    },
    {
      question: "What is the process of nuclear fission used for?",
      option1: "Generating electricity",
      option2: "Food preservation",
      option3: "Carbon dating",
      option4: "Desalination",
      ans: 1,
    },
    {
      question: "In mathematics, what is a 'quadratic equation'?",
      option1: "An equation with one variable",
      option2: "An equation with two variables",
      option3: "An equation of the form ax^2 + bx + c = 0",
      option4: "An equation involving square roots",
      ans: 3,
    },
    {
      question: "What is the chemical formula for table salt?",
      option1: "NaCl",
      option2: "HCl",
      option3: "KCl",
      option4: "CaCl2",
      ans: 1,
    },
    {
      question: "Who is known as the 'Father of Modern Physics'?",
      option1: "Isaac Newton",
      option2: "Albert Einstein",
      option3: "Galileo Galilei",
      option4: "Niels Bohr",
      ans: 2,
    },
    {
      question: "What is the process by which rocks break down into smaller particles?",
      option1: "Erosion",
      option2: "Deposition",
      option3: "Weathering",
      option4: "Crystallization",
      ans: 3,
    },
    {
      question: "Which Indian state is known as the 'Spice Garden of India'?",
      option1: "Kerala",
      option2: "Karnataka",
      option3: "Andhra Pradesh",
      option4: "Tamil Nadu",
      ans: 1,
    },
  ];
  export default class12Questions;