export const class11Questions = [
    {
      question: "Who formulated the laws of motion?",
      option1: "Isaac Newton",
      option2: "Albert Einstein",
      option3: "Galileo Galilei",
      option4: "Niels Bohr",
      ans: 1,
    },
    {
      question: "What is the chemical formula for sulfuric acid?",
      option1: "HCl",
      option2: "H2SO4",
      option3: "CH4",
      option4: "NaOH",
      ans: 2,
    },
    {
      question: "Which Indian state is known as the 'Land of Five Rivers'?",
      option1: "Punjab",
      option2: "Haryana",
      option3: "Uttar Pradesh",
      option4: "Rajasthan",
      ans: 1,
    },
    {
      question: "In physics, what is the equation for work done?",
      option1: "W = Fd",
      option2: "W = F/a",
      option3: "W = ma",
      option4: "W = Pt",
      ans: 1,
    },
    {
      question: "Who developed the theory of relativity along with Albert Einstein?",
      option1: "Niels Bohr",
      option2: "Max Planck",
      option3: "Werner Heisenberg",
      option4: "Mileva Marić",
      ans: 4,
    },
    {
      question: "What is the capital city of Brazil?",
      option1: "Rio de Janeiro",
      option2: "Brasília",
      option3: "Sao Paulo",
      option4: "Buenos Aires",
      ans: 2,
    },
    {
      question: "In chemistry, what is Avogadro's number?",
      option1: "6.02 x 10^23",
      option2: "3.14 x 10^5",
      option3: "9.81 x 10^2",
      option4: "2.20 x 10^4",
      ans: 1,
    },
    {
      question: "Who proposed the theory of continental drift?",
      option1: "Alfred Wegener",
      option2: "Charles Darwin",
      option3: "Isaac Newton",
      option4: "Ernest Rutherford",
      ans: 1,
    },
    {
      question: "Which Indian river is known as the 'Ganga of the South'?",
      option1: "Yamuna",
      option2: "Krishna",
      option3: "Godavari",
      option4: "Brahmaputra",
      ans: 3,
    },
    {
      question: "What is the unit of electric charge?",
      option1: "Ampere",
      option2: "Coulomb",
      option3: "Volt",
      option4: "Ohm",
      ans: 2,
    },
    {
      question: "Who wrote the book 'Origin of Species'?",
      option1: "Charles Darwin",
      option2: "Gregor Mendel",
      option3: "Alfred Russel Wallace",
      option4: "Stephen Hawking",
      ans: 1,
    },
    {
      question: "What is the formula for the volume of a cylinder?",
      option1: "V = πr^2h",
      option2: "V = πrh",
      option3: "V = 2πrh",
      option4: "V = (4/3)πr^3",
      ans: 1,
    },
    {
      question: "Which gas is responsible for the smell of rotten eggs?",
      option1: "Hydrogen",
      option2: "Sulfur Dioxide",
      option3: "Methane",
      option4: "Ammonia",
      ans: 2,
    },
    {
      question: "Who discovered the double helix structure of DNA?",
      option1: "James Watson and Francis Crick",
      option2: "Rosalind Franklin",
      option3: "Linus Pauling",
      option4: "Gregor Mendel",
      ans: 1,
    },
    {
      question: "What is the SI unit of pressure?",
      option1: "Newton",
      option2: "Pascal",
      option3: "Watt",
      option4: "Joule",
      ans: 2,
    },
    {
      question: "What is the chemical formula for hydrogen peroxide?",
      option1: "H2O2",
      option2: "H2SO4",
      option3: "CO2",
      option4: "NaCl",
      ans: 1,
    },
    {
      question: "Who is known as the 'Father of Modern Chemistry'?",
      option1: "Antoine Lavoisier",
      option2: "Dmitri Mendeleev",
      option3: "John Dalton",
      option4: "Robert Boyle",
      ans: 1,
    },
    {
      question: "What is the process by which plants lose water through their leaves?",
      option1: "Photosynthesis",
      option2: "Respiration",
      option3: "Transpiration",
      option4: "Evaporation",
      ans: 3,
    },
    {
      question: "Which Indian state is the largest producer of coffee?",
      option1: "Kerala",
      option2: "Karnataka",
      option3: "Tamil Nadu",
      option4: "Andhra Pradesh",
      ans: 2,
    },
    {
      question: "What is the half-life of a radioactive substance?",
      option1: "The time taken for half of the substance to decay",
      option2: "The time taken for the substance to reach half of its initial quantity",
      option3: "The time taken for the substance to become stable",
      option4: "The time taken for the substance to lose half of its energy",
      ans: 1,
    },
    {
      question: "Who is the author of the book 'The God of Small Things'?",
      option1: "Arundhati Roy",
      option2: "Salman Rushdie",
      option3: "Ruskin Bond",
      option4: "Vikram Seth",
      ans: 1,
    },
    {
      question: "What is the value of the mathematical constant 'π' (pi) to four decimal places?",
      option1: "3.1415",
      option2: "3.1428",
      option3: "3.1452",
      option4: "3.1479",
      ans: 1,
    },
    {
      question: "In physics, what is the equation for work done?",
      option1: "W = Fd",
      option2: "W = F/a",
      option3: "W = ma",
      option4: "W = Pt",
      ans: 1,
    },
    {
      question: "Which gas is known as 'laughing gas'?",
      option1: "Nitrous Oxide",
      option2: "Carbon Dioxide",
      option3: "Oxygen",
      option4: "Methane",
      ans: 1,
    },
  ];
  export default class11Questions;