export const class4Questions = [
    {
      question: "What is the capital of France?",
      option1: "Berlin",
      option2: "Rome",
      option3: "Madrid",
      option4: "Paris",
      ans: 4,
    },
    {
      question: "Who is the President of the United States?",
      option1: "Joe Biden",
      option2: "Donald Trump",
      option3: "Barack Obama",
      option4: "George Bush",
      ans: 1,
    },
    {
      question: "What is the result of 15 ÷ 3?",
      option1: "3",
      option2: "5",
      option3: "7",
      option4: "9",
      ans: 2,
    },
    {
      question: "Which planet is known as the 'Blue Planet'?",
      option1: "Mars",
      option2: "Earth",
      option3: "Jupiter",
      option4: "Neptune",
      ans: 2,
    },
    {
      question: "Who invented the telephone?",
      option1: "Thomas Edison",
      option2: "Alexander Graham Bell",
      option3: "Nikola Tesla",
      option4: "Marconi",
      ans: 2,
    },
    {
      question: "What is the square of 7?",
      option1: "42",
      option2: "49",
      option3: "56",
      option4: "64",
      ans: 2,
    },
    {
      question: "Which gas do plants absorb from the atmosphere?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Nitrogen",
      option4: "Hydrogen",
      ans: 2,
    },
    {
      question: "What is the largest mammal on Earth?",
      option1: "Elephant",
      option2: "Blue Whale",
      option3: "Giraffe",
      option4: "Lion",
      ans: 2,
    },
    {
      question: "In which year did India become a republic?",
      option1: "1947",
      option2: "1950",
      option3: "1965",
      option4: "1971",
      ans: 2,
    },
    {
      question: "What is the capital of Japan?",
      option1: "Seoul",
      option2: "Tokyo",
      option3: "Beijing",
      option4: "Bangkok",
      ans: 2,
    },
    {
      question: "What is the result of 8 x 9?",
      option1: "64",
      option2: "72",
      option3: "80",
      option4: "92",
      ans: 2,
    },
    {
      question: "Which gas makes up the majority of the Earth's atmosphere?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Nitrogen",
      option4: "Argon",
      ans: 3,
    },
    {
      question: "Who was the first woman to win a Nobel Prize?",
      option1: "Marie Curie",
      option2: "Rosa Parks",
      option3: "Mother Teresa",
      option4: "Indira Gandhi",
      ans: 1,
    },
    {
      question: "What is the result of 18 - 7?",
      option1: "8",
      option2: "9",
      option3: "10",
      option4: "11",
      ans: 3,
    },
    {
      question: "What is the chemical symbol for gold?",
      option1: "Au",
      option2: "Ag",
      option3: "Fe",
      option4: "Cu",
      ans: 1,
    },
    {
      question: "Who discovered gravity?",
      option1: "Isaac Newton",
      option2: "Galileo Galilei",
      option3: "Albert Einstein",
      option4: "Stephen Hawking",
      ans: 1,
    },
    {
      question: "What is the result of 5³?",
      option1: "100",
      option2: "125",
      option3: "150",
      option4: "175",
      ans: 2,
    },
    {
      question: "Which planet is known as the 'Ringed Planet'?",
      option1: "Saturn",
      option2: "Uranus",
      option3: "Neptune",
      option4: "Pluto",
      ans: 1,
    },
    {
      question: "What is the capital of Russia?",
      option1: "Moscow",
      option2: "St. Petersburg",
      option3: "Kiev",
      option4: "Minsk",
      ans: 1,
    },
    {
      question: "What is the result of 12 ÷ 4?",
      option1: "2",
      option2: "3",
      option3: "4",
      option4: "5",
      ans: 3,
    },
    {
      question: "Who wrote 'Romeo and Juliet'?",
      option1: "Charles Dickens",
      option2: "William Shakespeare",
      option3: "Jane Austen",
      option4: "Leo Tolstoy",
      ans: 2,
    },
    {
      question: "What is the smallest prime number greater than 10?",
      option1: "11",
      option2: "13",
      option3: "15",
      option4: "17",
      ans: 1,
    },
    {
      question: "What is the result of 7 x 6?",
      option1: "36",
      option2: "42",
      option3: "48",
      option4: "54",
      ans: 2,
    },
    {
      question: "Which planet is known as the 'Evening Star'?",
      option1: "Mercury",
      option2: "Venus",
      option3: "Mars",
      option4: "Jupiter",
      ans: 2,
    },
    {
      question: "What is the result of 9 + 3 × 2?",
      option1: "15",
      option2: "18",
      option3: "21",
      option4: "24",
      ans: 3,
    },
  ];
  export  default class4Questions;    