export const class7Questions = [
    {
      question: "Who is known as the 'Father of Modern Physics'?",
      option1: "Isaac Newton",
      option2: "Niels Bohr",
      option3: "Albert Einstein",
      option4: "Galileo Galilei",
      ans: 3,
    },
    {
      question: "What is the capital of Australia?",
      option1: "Sydney",
      option2: "Melbourne",
      option3: "Canberra",
      option4: "Brisbane",
      ans: 3,
    },
    {
      question: "Simplify: (2/3) * (4/5) ÷ (1/2).",
      option1: "4/5",
      option2: "3/5",
      option3: "2/3",
      option4: "1/2",
      ans: 1,
    },
    {
      question: "Which gas is known as the 'Greenhouse Gas'?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Methane",
      option4: "Nitrous Oxide",
      ans: 2,
    },
    {
      question: "Who discovered penicillin?",
      option1: "Alexander Fleming",
      option2: "Louis Pasteur",
      option3: "Joseph Lister",
      option4: "Marie Curie",
      ans: 1,
    },
    {
      question: "What is the result of 3⁴?",
      option1: "81",
      option2: "64",
      option3: "27",
      option4: "243",
      ans: 2,
    },
    {
      question: "In the periodic table, what is the symbol for gold?",
      option1: "Au",
      option2: "Ag",
      option3: "Fe",
      option4: "Cu",
      ans: 1,
    },
    {
      question: "Who is the Chief Justice of India as of 2023?",
      option1: "N.V. Ramana",
      option2: "Sharad Arvind Bobde",
      option3: "Ranjan Gogoi",
      option4: "Dipak Misra",
      ans: 1,
    },
    {
      question: "What is the result of √144?",
      option1: "10",
      option2: "12",
      option3: "14",
      option4: "16",
      ans: 2,
    },
    {
      question: "Which gas is produced during photosynthesis?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Nitrogen",
      option4: "Hydrogen",
      ans: 1,
    },
    {
      question: "Solve for x: 2x + 5 = 15.",
      option1: "5",
      option2: "6",
      option3: "7",
      option4: "8",
      ans: 1,
    },
    {
      question: "Who wrote the play 'Macbeth'?",
      option1: "William Shakespeare",
      option2: "Jane Austen",
      option3: "Leo Tolstoy",
      option4: "Charles Dickens",
      ans: 1,
    },
    {
      question: "What is the result of 18 - 4 ÷ 2?",
      option1: "10",
      option2: "12",
      option3: "14",
      option4: "16",
      ans: 3,
    },
    {
      question: "Which river is known as the 'Ganges' in India?",
      option1: "Yamuna",
      option2: "Brahmaputra",
      option3: "Indus",
      option4: "Ganga",
      ans: 4,
    },
    {
      question: "What is the result of log₂8?",
      option1: "2",
      option2: "3",
      option3: "4",
      option4: "5",
      ans: 3,
    },
    {
      question: "If the sum of the angles in a hexagon is 720 degrees, what is the measure of each angle?",
      option1: "120 degrees",
      option2: "140 degrees",
      option3: "150 degrees",
      option4: "160 degrees",
      ans: 1,
    },
    {
      question: "Who discovered the structure of DNA?",
      option1: "James Watson",
      option2: "Francis Crick",
      option3: "Rosalind Franklin",
      option4: "Linus Pauling",
      ans: 2,
    },
    {
      question: "What is the result of 13 + 5 × 2?",
      option1: "26",
      option2: "28",
      option3: "30",
      option4: "32",
      ans: 2,
    },
    {
      question: "Which Indian state is known as the 'Land of Five Rivers'?",
      option1: "Punjab",
      option2: "Haryana",
      option3: "Rajasthan",
      option4: "Gujarat",
      ans: 1,
    },
    {
      question: "Find the area of a rectangle with length 15 cm and width 8 cm.",
      option1: "120 cm²",
      option2: "105 cm²",
      option3: "90 cm²",
      option4: "64 cm²",
      ans: 2,
    },
    {
      question: "What is the result of cos(45 degrees)?",
      option1: "0.5",
      option2: "0.707",
      option3: "0.866",
      option4: "1",
      ans: 2,
    },
    {
      question: "Which planet is known as the 'Red Planet'?",
      option1: "Mars",
      option2: "Venus",
      option3: "Jupiter",
      option4: "Saturn",
      ans: 1,
    },
    {
      question: "In chemistry, what does the pH scale measure?",
      option1: "Temperature",
      option2: "Acidity",
      option3: "Pressure",
      option4: "Density",
      ans: 2,
    },
    {
      question: "What is the result of 5² + 3³?",
      option1: "50",
      option2: "64",
      option3: "78",
      option4: "92",
      ans: 3,
    },
    {
      question: "Who is the author of the book 'The Discovery of India'?",
      option1: "Rabindranath Tagore",
      option2: "Jawaharlal Nehru",
      option3: "Sarojini Naidu",
      option4: "Mulk Raj Anand",
      ans: 2,
    },
  ];
  export default class7Questions;