export const class6Questions = [
    {
      question: "Who is the author of the book 'To Kill a Mockingbird'?",
      option1: "J.K. Rowling",
      option2: "Harper Lee",
      option3: "George Orwell",
      option4: "Jane Austen",
      ans: 2,
    },
    {
      question: "In which year did India gain independence?",
      option1: "1945",
      option2: "1947",
      option3: "1950",
      option4: "1962",
      ans: 2,
    },
    {
      question: "What is the result of 18 ÷ 3?",
      option1: "4",
      option2: "6",
      option3: "8",
      option4: "12",
      ans: 2,
    },
    {
      question: "Which gas is responsible for the depletion of the ozone layer?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Chlorofluorocarbons (CFCs)",
      option4: "Nitrogen",
      ans: 3,
    },
    {
      question: "Who wrote the play 'Romeo and Juliet'?",
      option1: "Charles Dickens",
      option2: "William Shakespeare",
      option3: "Jane Austen",
      option4: "Leo Tolstoy",
      ans: 2,
    },
    {
      question: "What is the result of 13²?",
      option1: "156",
      option2: "169",
      option3: "182",
      option4: "195",
      ans: 2,
    },
    {
      question: "Which planet is known as the 'Giant Planet'?",
      option1: "Mars",
      option2: "Earth",
      option3: "Jupiter",
      option4: "Venus",
      ans: 3,
    },
    {
      question: "What is the capital of Australia?",
      option1: "Sydney",
      option2: "Melbourne",
      option3: "Canberra",
      option4: "Brisbane",
      ans: 3,
    },
    {
      question: "What is the result of 9 x 7?",
      option1: "56",
      option2: "63",
      option3: "72",
      option4: "81",
      ans: 2,
    },
    {
      question: "Who discovered the theory of relativity?",
      option1: "Isaac Newton",
      option2: "Galileo Galilei",
      option3: "Albert Einstein",
      option4: "Stephen Hawking",
      ans: 3,
    },
    {
      question: "Which river is the longest in the world?",
      option1: "Nile",
      option2: "Amazon",
      option3: "Yangtze",
      option4: "Mississippi",
      ans: 1,
    },
    {
      question: "What is the result of 15 + 4 × 2?",
      option1: "23",
      option2: "27",
      option3: "33",
      option4: "38",
      ans: 1,
    },
    {
      question: "Who was the first woman to win a Nobel Prize in Chemistry?",
      option1: "Marie Curie",
      option2: "Dorothy Crowfoot Hodgkin",
      option3: "Ada E. Yonath",
      option4: "Frances H. Arnold",
      ans: 1,
    },
    {
      question: "What is the result of 20 - 9?",
      option1: "9",
      option2: "10",
      option3: "11",
      option4: "12",
      ans: 2,
    },
    {
      question: "What is the chemical symbol for water?",
      option1: "H2O",
      option2: "CO2",
      option3: "O2",
      option4: "N2",
      ans: 1,
    },
    {
      question: "Who was the first man to step on the moon?",
      option1: "Neil Armstrong",
      option2: "Buzz Aldrin",
      option3: "Yuri Gagarin",
      option4: "Michael Collins",
      ans: 1,
    },
    {
      question: "What is the result of 16 ÷ 2?",
      option1: "6",
      option2: "8",
      option3: "10",
      option4: "12",
      ans: 2,
    },
    {
      question: "Who wrote the book '1984'?",
      option1: "George Orwell",
      option2: "Aldous Huxley",
      option3: "Ray Bradbury",
      option4: "H.G. Wells",
      ans: 1,
    },
    {
      question: "What is the capital of South Korea?",
      option1: "Seoul",
      option2: "Tokyo",
      option3: "Beijing",
      option4: "Bangkok",
      ans: 1,
    },
    {
      question: "What is the result of 14 + 6 × 3?",
      option1: "24",
      option2: "32",
      option3: "38",
      option4: "44",
      ans: 4,
    },
    {
      question: "Which gas is known as the 'Silent Killer'?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Methane",
      option4: "Radon",
      ans: 4,
    },
    {
      question: "Who discovered the laws of motion?",
      option1: "Isaac Newton",
      option2: "Galileo Galilei",
      option3: "Albert Einstein",
      option4: "Stephen Hawking",
      ans: 1,
    },
    {
      question: "What is the result of 7³?",
      option1: "343",
      option2: "357",
      option3: "371",
      option4: "385",
      ans: 1,
    },
    {
      question: "Which Indian state is known as the 'Land of Five Rivers'?",
      option1: "Haryana",
      option2: "Punjab",
      option3: "Rajasthan",
      option4: "Gujarat",
      ans: 2,
    },
    {
      question: "What is the result of 15 + 3 × 2?",
      option1: "18",
      option2: "21",
      option3: "24",
      option4: "27",
      ans: 3,
    },
  ];
  export default class6Questions;