export const class8Questions = [
    {
      question: "What is the formula for the Pythagorean theorem?",
      option1: "a^2 + b^2 = c^2",
      option2: "a^2 - b^2 = c^2",
      option3: "a + b = c",
      option4: "a - b = c",
      ans: 1,
    },
    {
      question: "Which gas is responsible for the greenhouse effect?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Methane",
      option4: "Nitrogen",
      ans: 2,
    },
    {
      question: "Who discovered the structure of DNA?",
      option1: "Watson and Crick",
      option2: "Rosalind Franklin",
      option3: "Gregor Mendel",
      option4: "James Watson",
      ans: 1,
    },
    {
      question: "In which year was the first successful manned moon landing?",
      option1: "1965",
      option2: "1969",
      option3: "1972",
      option4: "1975",
      ans: 2,
    },
    {
      question: "What is the value of π (pi) to two decimal places?",
      option1: "3.14",
      option2: "3.16",
      option3: "3.18",
      option4: "3.20",
      ans: 1,
    },
    {
      question: "Which scientist is known for the theory of relativity?",
      option1: "Isaac Newton",
      option2: "Galileo Galilei",
      option3: "Albert Einstein",
      option4: "Stephen Hawking",
      ans: 3,
    },
    {
      question: "What is the chemical formula for methane?",
      option1: "CH3",
      option2: "CO2",
      option3: "C2H6",
      option4: "H2O",
      ans: 1,
    },
    {
      question: "What is the capital city of Australia?",
      option1: "Canberra",
      option2: "Sydney",
      option3: "Melbourne",
      option4: "Brisbane",
      ans: 1,
    },
    {
      question: "Who developed the periodic table of elements?",
      option1: "Dmitri Mendeleev",
      option2: "Marie Curie",
      option3: "Niels Bohr",
      option4: "Ernest Rutherford",
      ans: 1,
    },
    {
      question: "What is the process by which plants make their own food?",
      option1: "Photosynthesis",
      option2: "Respiration",
      option3: "Transpiration",
      option4: "Fermentation",
      ans: 1,
    },
    {
      question: "What is the formula for calculating the area of a triangle?",
      option1: "A = bh",
      option2: "A = (bh)/2",
      option3: "A = lw",
      option4: "A = l + w",
      ans: 2,
    },
    {
      question: "Which gas is known as laughing gas?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Nitrous Oxide",
      option4: "Hydrogen",
      ans: 3,
    },
    {
      question: "What is the SI unit of electric current?",
      option1: "Watt",
      option2: "Volt",
      option3: "Ampere",
      option4: "Ohm",
      ans: 3,
    },
    {
      question: "Who formulated the laws of motion?",
      option1: "Isaac Newton",
      option2: "Galileo Galilei",
      option3: "Albert Einstein",
      option4: "Nikola Tesla",
      ans: 1,
    },
    {
      question: "What is the chemical symbol for lead?",
      option1: "Fe",
      option2: "Pb",
      option3: "Ag",
      option4: "Au",
      ans: 2,
    },
    {
      question: "Which organ in the human body produces insulin?",
      option1: "Liver",
      option2: "Pancreas",
      option3: "Kidney",
      option4: "Heart",
      ans: 2,
    },
    {
      question: "What is the unit of measurement for frequency?",
      option1: "Watt",
      option2: "Hertz",
      option3: "Newton",
      option4: "Joule",
      ans: 2,
    },
    {
      question: "Which Indian river is known as the 'Sorrow of Bihar'?",
      option1: "Yamuna",
      option2: "Ganges",
      option3: "Kosi",
      option4: "Brahmaputra",
      ans: 3,
    },
    {
      question: "What is the largest bone in the human body?",
      option1: "Femur",
      option2: "Radius",
      option3: "Tibia",
      option4: "Humerus",
      ans: 1,
    },
    {
      question: "What is the speed of light in a vacuum?",
      option1: "300,000 km/s",
      option2: "150,000 km/s",
      option3: "500,000 km/s",
      option4: "750,000 km/s",
      ans: 1,
    },
    {
      question: "Who proposed the theory of evolution by natural selection?",
      option1: "Charles Darwin",
      option2: "Gregor Mendel",
      option3: "Alfred Russel Wallace",
      option4: "Jean-Baptiste Lamarck",
      ans: 1,
    },
    {
      question: "What is the chemical symbol for sodium?",
      option1: "Na",
      option2: "Ne",
      option3: "Ni",
      option4: "N",
      ans: 1,
    },
    {
      question: "In mathematics, what is a prime number?",
      option1: "A number divisible by 2",
      option2: "A number divisible by 3",
      option3: "A number divisible by 1 and itself",
      option4: "A number divisible by 5",
      ans: 3,
    },
    {
      question: "What is the formula for acceleration?",
      option1: "a = v/t",
      option2: "a = s/t",
      option3: "a = v/s",
      option4: "a = s/v",
      ans: 1,
    },
    {
      question: "Which gas is used for the extinguishing of fires?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Nitrogen",
      option4: "Argon",
      ans: 2,
    },
  ];
  export default class8Questions;