export const class1Questions = [
    {
      question: "What is the capital city of India?",
      option1: "Mumbai",
      option2: "New Delhi",
      option3: "Kolkata",
      option4: "Chennai",
      ans: 2,
    },
    {
      question: "Who is the current Prime Minister of India?",
      option1: "Narendra Modi",
      option2: "Rahul Gandhi",
      option3: "Amit Shah",
      option4: "Sonia Gandhi",
      ans: 1,
    },
    {
      question: "If you have 3 apples and eat 1, how many apples do you have left?",
      option1: "0",
      option2: "1",
      option3: "2",
      option4: "3",
      ans: 2,
    },
    {
      question: "What do plants need to make their own food?",
      option1: "Sunlight, water, and air",
      option2: "Candy and toys",
      option3: "Electricity",
      option4: "Answer not given",
      ans: 1,
    },
    {
      question: "Which river is known as the 'Ganges' in India?",
      option1: "Yamuna",
      option2: "Brahmaputra",
      option3: "Indus",
      option4: "Ganga",
      ans: 4,
    },
    {
      question: "In which year did India gain independence?",
      option1: "1942",
      option2: "1947",
      option3: "1950",
      option4: "1965",
      ans: 2,
    },
    {
      question: "What is the result of 4 + 2?",
      option1: "5",
      option2: "6",
      option3: "7",
      option4: "8",
      ans: 2,
    },
    {
      question: "What is the color of the leaves in most trees?",
      option1: "Blue",
      option2: "Red",
      option3: "Green",
      option4: "Yellow",
      ans: 3,
    },
    {
      question: "Which famous monument in India is a symbol of love?",
      option1: "Qutub Minar",
      option2: "Red Fort",
      option3: "Taj Mahal",
      option4: "India Gate",
      ans: 3,
    },
    {
      question: "Which festival is celebrated to mark the victory of good over evil in India?",
      option1: "Diwali",
      option2: "Holi",
      option3: "Navratri",
      option4: "Durga Puja",
      ans: 1,
    },
    {
      question: "If you have 5 fingers on one hand, how many fingers do you have on both hands?",
      option1: "8",
      option2: "10",
      option3: "12",
      option4: "5",
      ans: 2,
    },
    {
      question: "What is the source of light in the daytime?",
      option1: "Moon",
      option2: "Stars",
      option3: "Sun",
      option4: "Candle",
      ans: 3,
    },
    {
      question: "Which animal is the national symbol of India?",
      option1: "Lion",
      option2: "Elephant",
      option3: "Tiger",
      option4: "Leopard",
      ans: 3,
    },
    {
      question: "What is the currency used in India?",
      option1: "Dollar",
      option2: "Rupee",
      option3: "Euro",
      option4: "Pound",
      ans: 2,
    },
    {
      question: "What is the result of 3 + 5?",
      option1: "6",
      option2: "7",
      option3: "8",
      option4: "9",
      ans: 8,
    },
    {
      question: "What do we use to see objects that are very far away?",
      option1: "Microscope",
      option2: "Telescope",
      option3: "Magnifying glass",
      option4: "Answer not given",
      ans: 2,
    },
    {
      question: "Which planet is known as the 'Red Planet'?",
      option1: "Mars",
      option2: "Venus",
      option3: "Jupiter",
      option4: "Saturn",
      ans: 1,
    },
    {
      question: "What is the national game of India?",
      option1: "Cricket",
      option2: "Hockey",
      option3: "Football",
      option4: "Tennis",
      ans: 2,
    },
    {
      question: "What comes after the number 10?",
      option1: "9",
      option2: "11",
      option3: "12",
      option4: "8",
      ans: 2,
    },
    {
      question: "Which of the following is a gas that we breathe in?",
      option1: "Oxygen",
      option2: "Carbon dioxide",
      option3: "Hydrogen",
      option4: "Nitrogen",
      ans: 1,
    },
    {
      question: "Which ocean is on the eastern coast of India?",
      option1: "Atlantic Ocean",
      option2: "Indian Ocean",
      option3: "Pacific Ocean",
      option4: "Arctic Ocean",
      ans: 2,
    },
    {
      question: "Who is known as the 'Father of the Nation' in India?",
      option1: "Jawaharlal Nehru",
      option2: "Subhas Chandra Bose",
      option3: "Mahatma Gandhi",
      option4: "Sardar Patel",
      ans: 3,
    },
    {
      question: "What is the shape of a square?",
      option1: "Circle",
      option2: "Triangle",
      option3: "Square",
      option4: "Rectangle",
      ans: 3,
    },
    {
      question: "Which part of the plant absorbs water and nutrients from the soil?",
      option1: "Roots",
      option2: "Leaves",
      option3: "Stem",
      option4: "Flower",
      ans: 1,
    },
  ];
  export default class1Questions;