export const class3Questions = [
    {
      question: "What is the largest planet in our solar system?",
      option1: "Earth",
      option2: "Mars",
      option3: "Jupiter",
      option4: "Venus",
      ans: 3,
    },
    {
      question: "Who is known as the 'Father of Computers'?",
      option1: "Alan Turing",
      option2: "Charles Babbage",
      option3: "Bill Gates",
      option4: "Steve Jobs",
      ans: 2,
    },
    {
      question: "What is the capital of Australia?",
      option1: "Sydney",
      option2: "Melbourne",
      option3: "Canberra",
      option4: "Brisbane",
      ans: 3,
    },
    {
      question: "How many continents are there in the world?",
      option1: "5",
      option2: "6",
      option3: "7",
      option4: "8",
      ans: 2,
    },
    {
      question: "What is the currency of Japan?",
      option1: "Yen",
      option2: "Dollar",
      option3: "Euro",
      option4: "Pound",
      ans: 1,
    },
    {
      question: "Who wrote 'Alice in Wonderland'?",
      option1: "J.K. Rowling",
      option2: "Lewis Carroll",
      option3: "Roald Dahl",
      option4: "Enid Blyton",
      ans: 2,
    },
    {
      question: "Which gas do plants release during photosynthesis?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Nitrogen",
      option4: "Hydrogen",
      ans: 1,
    },
    {
      question: "What is the capital of Brazil?",
      option1: "Buenos Aires",
      option2: "Rio de Janeiro",
      option3: "Brasília",
      option4: "Sao Paulo",
      ans: 3,
    },
    {
      question: "What is the result of 6 + 4?",
      option1: "8",
      option2: "10",
      option3: "12",
      option4: "14",
      ans: 2,
    },
    {
      question: "Who discovered penicillin?",
      option1: "Alexander Fleming",
      option2: "Marie Curie",
      option3: "Thomas Edison",
      option4: "Louis Pasteur",
      ans: 1,
    },
    {
      question: "What is the process by which plants make their own food?",
      option1: "Photosynthesis",
      option2: "Respiration",
      option3: "Digestion",
      option4: "Answer not given",
      ans: 1,
    },
    {
      question: "What is the smallest prime number?",
      option1: "0",
      option2: "1",
      option3: "2",
      option4: "3",
      ans: 3,
    },
    {
      question: "Who composed the famous symphony 'Ode to Joy'?",
      option1: "Beethoven",
      option2: "Mozart",
      option3: "Bach",
      option4: "Chopin",
      ans: 1,
    },
    {
      question: "How many sides does a pentagon have?",
      option1: "4",
      option2: "5",
      option3: "6",
      option4: "7",
      ans: 2,
    },
    {
      question: "What is the result of 9 - 3?",
      option1: "4",
      option2: "5",
      option3: "6",
      option4: "7",
      ans: 3,
    },
    {
      question: "What is the capital of South Africa?",
      option1: "Cape Town",
      option2: "Johannesburg",
      option3: "Pretoria",
      option4: "Durban",
      ans: 3,
    },
    {
      question: "Who is the author of 'The Jungle Book'?",
      option1: "Charles Dickens",
      option2: "Rudyard Kipling",
      option3: "Mark Twain",
      option4: "Jane Austen",
      ans: 2,
    },
    {
      question: "What is the result of 7 x 8?",
      option1: "49",
      option2: "56",
      option3: "64",
      option4: "72",
      ans: 2,
    },
    {
      question: "What is the capital of China?",
      option1: "Shanghai",
      option2: "Beijing",
      option3: "Guangzhou",
      option4: "Hong Kong",
      ans: 2,
    },
    {
      question: "What is the result of 12 ÷ 3?",
      option1: "2",
      option2: "3",
      option3: "4",
      option4: "5",
      ans: 3,
    },
    {
      question: "Which gas do humans exhale when they breathe out?",
      option1: "Oxygen",
      option2: "Carbon Dioxide",
      option3: "Nitrogen",
      option4: "Hydrogen",
      ans: 2,
    },
    {
      question: "Who is known as the 'Nightingale of India'?",
      option1: "Lata Mangeshkar",
      option2: "Asha Bhosle",
      option3: "Kishore Kumar",
      option4: "M.S. Subbulakshmi",
      ans: 4,
    },
    {
      question: "What is the result of 15 + 20?",
      option1: "30",
      option2: "35",
      option3: "40",
      option4: "45",
      ans: 3,
    },
    {
      question: "Which planet is known as the 'Morning Star'?",
      option1: "Mercury",
      option2: "Venus",
      option3: "Mars",
      option4: "Jupiter",
      ans: 2,
    },
    {
      question: "What is the result of 5²?",
      option1: "20",
      option2: "25",
      option3: "30",
      option4: "35",
      ans: 2,
    },
  ];
  export default class3Questions;