// export const data = [
//     {
//       question: "Which device is required for the Internet connection?",
//       option1: "Modem",
//       option2: "Router",
//       option3: "LAN Cable",
//       option4: "Pen Drive",
//       ans: 1,
//     },
//     {
//       question: "Which continent has the highest number of countries?",
//       option1: "Asia",
//       option2: "Europe",
//       option3: "North America",
//       option4: "Africa",
//       ans: 4,
//     },
//     {
//       question: "Junk e-mail is also called?",
//       option1: "Spam",
//       option2: "Fake",
//       option3: "Archived",
//       option4: "Bin",
//       ans: 1,
//     },
//     {
//       question: "A computer cannot BOOT if it does not have the?",
//       option1: "Application Software",
//       option2: "Internet",
//       option3: "Operating System",
//       option4: "Mouse",
//       ans: 3,
//     },
//     {
//       question: "First page of Website is termed as?",
//       option1: "Index Page",
//       option2: "Homepage",
//       option3: "Sitemap",
//       option4: "Pen Drive",
//       ans: 2,
//     },
//   ];



// export const data = [
//   {
//     question: "What is the capital city of Canada?",
//     option1: "Toronto",
//     option2: "Vancouver",
//     option3: "Ottawa",
//     option4: "Montreal",
//     ans: 3,
//   },
//   {
//     question: "How many continents are there on Earth?",
//     option1: "Five",
//     option2: "Six",
//     option3: "Seven",
//     option4: "Eight",
//     ans: 3,
//   },
//   {
//     question: "Who wrote 'Charlie and the Chocolate Factory'?",
//     option1: "Roald Dahl",
//     option2: "Enid Blyton",
//     option3: "J.K. Rowling",
//     option4: "Dr. Seuss",
//     ans: 1,
//   },
//   {
//     question: "What is the largest planet in our solar system?",
//     option1: "Earth",
//     option2: "Mars",
//     option3: "Jupiter",
//     option4: "Venus",
//     ans: 3,
//   },
//   {
//     question: "Which is the longest river in the world?",
//     option1: "Amazon",
//     option2: "Nile",
//     option3: "Yangtze",
//     option4: "Mississippi",
//     ans: 1,
//   },
//   {
//     question: "What is the currency of Japan?",
//     option1: "Yen",
//     option2: "Won",
//     option3: "Ringgit",
//     option4: "Peso",
//     ans: 1,
//   },
//   {
//     question: "How many sides does a hexagon have?",
//     option1: "Four",
//     option2: "Six",
//     option3: "Eight",
//     option4: "Ten",
//     ans: 2,
//   },
//   {
//     question: "Who painted the Mona Lisa?",
//     option1: "Pablo Picasso",
//     option2: "Vincent van Gogh",
//     option3: "Leonardo da Vinci",
//     option4: "Michelangelo",
//     ans: 3,
//   },
//   {
//     question: "What is the process by which plants make their own food?",
//     option1: "Photosynthesis",
//     option2: "Respiration",
//     option3: "Digestion",
//     option4: "Circulation",
//     ans: 1,
//   },
//   {
//     question: "What is the capital city of Australia?",
//     option1: "Sydney",
//     option2: "Melbourne",
//     option3: "Canberra",
//     option4: "Perth",
//     ans: 3,
//   },
//   {
//     question: "Who invented the light bulb?",
//     option1: "Thomas Edison",
//     option2: "Alexander Graham Bell",
//     option3: "Galileo Galilei",
//     option4: "Nikola Tesla",
//     ans: 1,
//   },
//   {
//     question: "What is the main function of the heart?",
//     option1: "Pumping Blood",
//     option2: "Digesting Food",
//     option3: "Filtering Water",
//     option4: "Producing Heat",
//     ans: 1,
//   },
//   {
//     question: "In what year did the Titanic sink?",
//     option1: "1905",
//     option2: "1912",
//     option3: "1923",
//     option4: "1931",
//     ans: 2,
//   },
//   {
//     question: "What is the largest mammal on Earth?",
//     option1: "Elephant",
//     option2: "Blue Whale",
//     option3: "Giraffe",
//     option4: "Hippopotamus",
//     ans: 2,
//   },
//   {
//     question: "Which planet is known as the 'Red Planet'?",
//     option1: "Earth",
//     option2: "Mars",
//     option3: "Jupiter",
//     option4: "Venus",
//     ans: 2,
//   },
//   {
//     question: "Who wrote 'The Cat in the Hat'?",
//     option1: "Dr. Seuss",
//     option2: "Beatrix Potter",
//     option3: "Roald Dahl",
//     option4: "A.A. Milne",
//     ans: 1,
//   },
//   {
//     question: "What is the smallest prime number?",
//     option1: "1",
//     option2: "2",
//     option3: "3",
//     option4: "5",
//     ans: 2,
//   },
//   {
//     question: "What is the capital city of China?",
//     option1: "Beijing",
//     option2: "Shanghai",
//     option3: "Hong Kong",
//     option4: "Tokyo",
//     ans: 1,
//   },
//   {
//     question: "What is the largest desert in the world?",
//     option1: "Sahara Desert",
//     option2: "Gobi Desert",
//     option3: "Arabian Desert",
//     option4: "Antarctica",
//     ans: 4,
//   },
//   {
//     question: "Who is known as the 'Father of Computers'?",
//     option1: "Bill Gates",
//     option2: "Alan Turing",
//     option3: "Steve Jobs",
//     option4: "Charles Babbage",
//     ans: 4,
//   },
//   {
//     question: "What is the currency of Brazil?",
//     option1: "Peso",
//     option2: "Dollar",
//     option3: "Real",
//     option4: "Euro",
//     ans: 3,
//   },
//   {
//     question: "What is the main ingredient in traditional Japanese sushi?",
//     option1: "Rice",
//     option2: "Noodles",
//     option3: "Seaweed",
//     option4: "Tofu",
//     ans: 1,
//   },
//   {
//     question: "What is the powerhouse of the cell?",
//     option1: "Nucleus",
//     option2: "Mitochondria",
//     option3: "Endoplasmic Reticulum",
//     option4: "Cell Membrane",
//     ans: 2,
//   },
//   {
//     question: "Who discovered penicillin?",
//     option1: "Marie Curie",
//     option2: "Alexander Fleming",
//     option3: "Louis Pasteur",
//     option4: "Gregor Mendel",
//     ans: 2,
//   },
// ];

// export default grade3Questions;




export const data = [
  {
    question: "What is the capital city of Brazil?",
    option1: "Rio de Janeiro",
    option2: "Sao Paulo",
    option3: "Brasilia",
    option4: "Buenos Aires",
    ans: 3,
  },
  {
    question: "Who wrote 'The Great Gatsby'?",
    option1: "F. Scott Fitzgerald",
    option2: "Ernest Hemingway",
    option3: "Jane Austen",
    option4: "Charles Dickens",
    ans: 1,
  },
  {
    question: "What is the currency of South Korea?",
    option1: "Yen",
    option2: "Won",
    option3: "Ringgit",
    option4: "Dollar",
    ans: 2,
  },
  {
    question: "Who developed the theory of relativity?",
    option1: "Isaac Newton",
    option2: "Albert Einstein",
    option3: "Galileo Galilei",
    option4: "Stephen Hawking",
    ans: 2,
  },
  {
    question: "What is the capital city of South Africa?",
    option1: "Cape Town",
    option2: "Johannesburg",
    option3: "Pretoria",
    option4: "Durban",
    ans: 1,
  },
  {
    question: "Which planet is known as the 'Red Planet'?",
    option1: "Earth",
    option2: "Mars",
    option3: "Jupiter",
    option4: "Venus",
    ans: 2,
  },
  {
    question: "What is the longest river in Asia?",
    option1: "Ganges",
    option2: "Yangtze",
    option3: "Mekong",
    option4: "Indus",
    ans: 2,
  },
  {
    question: "Who was the first woman to win a Nobel Prize?",
    option1: "Marie Curie",
    option2: "Mother Teresa",
    option3: "Rosalind Franklin",
    option4: "Malala Yousafzai",
    ans: 1,
  },
  {
    question: "In what year did the Berlin Wall fall?",
    option1: "1989",
    option2: "1991",
    option3: "1995",
    option4: "2000",
    ans: 1,
  },
  {
    question: "What is the capital city of Canada?",
    option1: "Toronto",
    option2: "Vancouver",
    option3: "Ottawa",
    option4: "Montreal",
    ans: 3,
  },
  {
    question: "Who wrote 'Pride and Prejudice'?",
    option1: "Jane Austen",
    option2: "Charlotte Bronte",
    option3: "Emily Dickinson",
    option4: "William Faulkner",
    ans: 1,
  },
  {
    question: "What is the currency of Japan?",
    option1: "Yen",
    option2: "Won",
    option3: "Ringgit",
    option4: "Peso",
    ans: 1,
  },
  {
    question: "Who discovered penicillin?",
    option1: "Marie Curie",
    option2: "Alexander Fleming",
    option3: "Louis Pasteur",
    option4: "Gregor Mendel",
    ans: 2,
  },
  {
    question: "What is the capital city of Mexico?",
    option1: "Mexico City",
    option2: "Cancun",
    option3: "Guadalajara",
    option4: "Monterrey",
    ans: 1,
  },
  {
    question: "Who wrote 'Romeo and Juliet'?",
    option1: "William Shakespeare",
    option2: "Jane Austen",
    option3: "Charles Dickens",
    option4: "Mark Twain",
    ans: 1,
  },
  {
    question: "What is the largest ocean on Earth?",
    option1: "Atlantic",
    option2: "Indian",
    option3: "Arctic",
    option4: "Pacific",
    ans: 4,
  },
  {
    question: "What is the capital city of China?",
    option1: "Beijing",
    option2: "Shanghai",
    option3: "Hong Kong",
    option4: "Tokyo",
    ans: 1,
  },
  {
    question: "Who was the first President of the United States?",
    option1: "Thomas Jefferson",
    option2: "John Adams",
    option3: "George Washington",
    option4: "Abraham Lincoln",
    ans: 3,
  },
  {
    question: "What is the main ingredient in traditional Japanese sushi?",
    option1: "Rice",
    option2: "Noodles",
    option3: "Seaweed",
    option4: "Tofu",
    ans: 1,
  },
  {
    question: "What is the smallest prime number?",
    option1: "1",
    option2: "2",
    option3: "3",
    option4: "5",
    ans: 2,
  },
  {
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    option1: "Amelia Earhart",
    option2: "Bessie Coleman",
    option3: "Harriet Quimby",
    option4: "Jacqueline Cochran",
    ans: 1,
  },
  {
    question: "What is the capital city of Argentina?",
    option1: "Rio de Janeiro",
    option2: "Sao Paulo",
    option3: "Buenos Aires",
    option4: "Montevideo",
    ans: 3,
  },
  {
    question: "Who wrote 'The Diary of a Young Girl'?",
    option1: "Anne Frank",
    option2: "Harper Lee",
    option3: "J.K. Rowling",
    option4: "George Orwell",
    ans: 1,
  },
  {
    question: "What is the largest desert in the world?",
    option1: "Sahara Desert",
    option2: "Gobi Desert",
    option3: "Arabian Desert",
    option4: "Antarctica",
    ans: 4,
  },
];

// export default grade7Questions;